services:
  fastapi-server:
    build: ./src
    command: "uvicorn src.main:app --reload --host 0.0.0.0 --port 20001"
    ports:
      - 8000:20001
    volumes:
      - ./:/src

  fastapi-client:
    build: ./src
    command: "uvicorn src.client:app --reload --host 0.0.0.0 --port 20001"
    ports:
      - 8001:20001
    volumes:
      - ./:/src
    extra_hosts:
      # - "host.docker.internal:20003"
      - "host.docker.internal:host-gateway"
